name: Update Branch
on:
  push:
    branches-ignore:
      - main
jobs:
  updateBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update branch
          title: Update branch
          body: Credit new contributors
          branch: ${{ github.ref }}
          base: main
